name: Check for new Nuclei templates

on:
  schedule:
    - cron: '0 5 * * *' # Раз в день в 05:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false # Управляем кэшем вручную

      # ШАГ 1: Восстанавливаем кэш Go модулей, если он есть
      - name: Restore Go modules cache
        id: cache-go-restore
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # ШАГ 2: Устанавливаем зависимости. go mod tidy создаст/обновит go.sum
      # Этот шаг теперь не упадет, даже если go.sum нет, он его создаст.
      - name: Install dependencies
        run: go mod tidy

      # ШАГ 3: Восстанавливаем кэш файлов состояния (known_templates)
      - name: Restore state files cache
        id: cache-state-restore
        uses: actions/cache@v4
        with:
          path: known_templates_*.txt
          key: ${{ runner.os }}-state-${{ hashFiles('known_templates_*.txt') }}
          restore-keys: |
            ${{ runner.os }}-state-

      - name: Run checker
        run: go run main.go

      # ШАГ 4: Сохраняем кэш файлов состояния
      # Этот шаг выполняется в post-execution фазе экшена cache
      # Он автоматически сохранит кэш, если ключ изменился (т.е. файлы были обновлены)
      # Ничего дополнительно делать не нужно, шаг cache-state-restore сам об этом позаботится.
