name: Check for new Nuclei templates

on:
  schedule:
    - cron: '0 5 * * *' # Исправлен cron: каждый день в 05:00 UTC
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  check-templates:
    runs-on: ubuntu-latest
    
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false # Отключаем автоматическое кэширование Go
          
      # Создаем go.sum если его нет
      - name: Initialize Go modules
        run: |
          if [ ! -f go.sum ]; then
            go mod tidy
          fi
          
      # Восстанавливаем файлы состояния из кэша
      - name: Restore state files
        uses: actions/cache/restore@v4
        with:
          path: |
            known_templates_*.txt
          key: ${{ runner.os }}-templates-state-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-templates-state-
            
      # Запускаем проверку
      - name: Run nuclei templates checker
        run: go run main.go
        
      # Сохраняем обновленные файлы состояния
      - name: Save state files
        uses: actions/cache/save@v4
        if: always() # Сохраняем даже если предыдущий шаг упал
        with:
          path: |
            known_templates_*.txt
          key: ${{ runner.os }}-templates-state-${{ github.run_id }}
          
      # Дебаг информация (можно убрать после отладки)
      - name: Debug info
        if: always()
        run: |
          echo "=== Files in directory ==="
          ls -la
          echo "=== State files ==="
          ls -la known_templates_*.txt || echo "No state files found"
