name: Check for new Nuclei templates

on:
  # Запускать по расписанию
  schedule:
    - cron: '0 5 * * *'
  # Настройки для ручного запуска
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Запустить в тестовом режиме? (true/false)'
        required: true
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Передаем секреты в переменные окружения для ВСЕХ шагов
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      # В этом шаге мы передаем только тестовый флаг,
      # а секреты уже доступны благодаря 'env' на уровне 'jobs'
      - name: Run checker
        run: go run main.go
        env:
          FORCE_TEST_NOTIFICATION: ${{ inputs.test_mode }}
