name: Check for new Nuclei templates

on:
  # Запускать по расписанию: раз в день в 05:00 UTC (8 утра по МСК)
  schedule:
    - cron: '0 5 * * *'
  # Позволяет запускать вручную с вкладки Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем код нашего Go-скрипта
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # 3. Запускаем наш скрипт, передавая ему секреты
      - name: Run checker
        run: go run main.go
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
