name: Check for new Nuclei templates

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Запустить в тестовом режиме? (true/false)'
        required: true
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      # ШАГ ДИАГНОСТИКИ: Показываем переменные, которые мы получили
      - name: Print Environment Variables
        run: |
          echo "Test mode input: ${{ inputs.test_mode }}"
          echo "Token Secret: ${{ secrets.TELEGRAM_BOT_TOKEN && 'found' || 'NOT FOUND' }}"
          echo "ChatID Secret: ${{ secrets.TELEGRAM_CHAT_ID && 'found' || 'NOT FOUND' }}"

      # Запускаем скрипт, передавая все переменные ЯВНО
      - name: Run checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_TEST_NOTIFICATION: ${{ inputs.test_mode }}
        run: go run main.go
