name: Check for new Nuclei templates

on:
  schedule:
    - cron: '0 5 * * *' # Раз в день в 05:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false # Отключаем встроенное кэширование, чтобы управлять им вручную

      # --- Кэширование Go-модулей (НАДЕЖНЫЙ СПОСОБ) ---

      # ШАГ 1: Восстанавливаем кэш по общему ключу. Этот шаг никогда не упадет.
      - name: Restore Go modules cache
        id: cache-go-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/go/pkg/mod
          # Ищем любой кэш, начинающийся с этого префикса
          restore-keys: |
            ${{ runner.os }}-go-

      # ШАГ 2: Устанавливаем зависимости. go mod tidy создаст/обновит go.sum
      - name: Install dependencies
        run: go mod tidy

      # ШАГ 3: Сохраняем кэш Go-модулей. Этот шаг выполняется ПОСЛЕ go mod tidy.
      # Теперь hashFiles('**/go.sum') гарантированно сработает.
      - name: Save Go modules cache
        uses: actions/cache/save@v4
        with:
          path: ~/go/pkg/mod
          # Ключ для сохранения теперь будет точным, т.к. go.sum уже существует
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        # Условие: выполняем, только если кэш не был полностью восстановлен на шаге 1
        if: steps.cache-go-restore.outputs.cache-hit != 'true'

      # --- Кэширование файлов состояния (known_templates) ---
      
      # ШАГ 4: Восстанавливаем кэш состояния.
      # Этот шаг использует actions/cache, который сам обрабатывает и восстановление, и сохранение в конце.
      - name: Cache state files
        id: cache-state
        uses: actions/cache@v4
        with:
          path: known_templates_*.txt
          # Ключ основан на хэше файлов. При первом запуске хэш будет от несуществующих файлов (пустой),
          # а в конце работы будет вычислен новый хэш от созданных файлов и кэш будет сохранен.
          key: ${{ runner.os }}-state-${{ hashFiles('known_templates_*.txt') }}
          restore-keys: |
            ${{ runner.os }}-state-

      # ШАГ 5: Запускаем основной скрипт
      - name: Run checker
        run: go run main.go

